/-
# Formal Verification Example in Lean 4
## Verifying a Code Change: Adding a Guard Condition

Generated by Leanstral (labs-leanstral-2603).
All 13 theorems proven. No errors.

This example verifies a common software engineering pattern: adding a boolean
guard (`&& !userAborted`) to a condition that triggers a side effect, to prevent
the side effect from firing when the user has already requested cancellation.
-/

import Mathlib

namespace Example

variable (timedOut compactDuring timeExecuting userAborted : Bool)

-- Old conditions (before the fix)
def triggerOld : Bool := timedOut && !compactDuring && !timeExecuting
def flagOld : Bool := timedOut && !compactDuring && !timeExecuting

-- New conditions (after adding userAborted guard)
def triggerNew : Bool := timedOut && !compactDuring && !timeExecuting && !userAborted
def flagNew : Bool := timedOut && !compactDuring && !timeExecuting && !userAborted

-- ════════════════════════════════════════
-- Part 1: Trigger correctness
-- ════════════════════════════════════════

-- 1a: User abort always prevents the trigger
theorem user_abort_prevents (hA : userAborted = true) :
    triggerNew timedOut compactDuring timeExecuting userAborted = false := by
  simp [triggerNew, hA]

-- 1b: Non-user-abort preserves original behavior
theorem non_abort_preserved (hA : userAborted = false) :
    triggerNew timedOut compactDuring timeExecuting userAborted = triggerOld timedOut compactDuring timeExecuting := by
  simp [triggerNew, triggerOld, hA]

-- 1c: New trigger is strictly stricter (new=true implies old=true)
theorem new_implies_old :
    triggerNew timedOut compactDuring timeExecuting userAborted = true → triggerOld timedOut compactDuring timeExecuting = true := by
  intro h
  simp [triggerNew, triggerOld] at h ⊢
  tauto

-- 1d: The fix matters (witness where old=true and new=false)
theorem fix_matters :
    triggerOld true false false = true ∧
    triggerNew true false false true = false := by
  simp [triggerOld, triggerNew]

-- ════════════════════════════════════════
-- Part 2: Associated flag correctness
-- ════════════════════════════════════════

-- 2a: Flag has identical expression to trigger
theorem flag_eq_trigger :
    flagNew timedOut compactDuring timeExecuting userAborted = triggerNew timedOut compactDuring timeExecuting userAborted := by
  rfl

-- 2b: User abort means no flag
theorem user_abort_no_flag (hA : userAborted = true) :
    flagNew timedOut compactDuring timeExecuting userAborted = false := by
  simp [flagNew, hA]

-- 2c: Internal condition preserves original flag behavior
theorem internal_preserved_flag (hA : userAborted = false) :
    flagNew timedOut compactDuring timeExecuting userAborted = flagOld timedOut compactDuring timeExecuting := by
  simp [flagNew, flagOld, hA]

-- ════════════════════════════════════════
-- Part 3: Source exclusivity
-- ════════════════════════════════════════

-- Model the abort source as an inductive type
inductive AbortSource
  | userStop
  | internalTimeout
  | idleTimeout

def isUserAbort : AbortSource → Bool
  | .userStop => true
  | .internalTimeout => false
  | .idleTimeout => false

-- 3a: Only userStop sets the user abort flag
theorem only_user_stop_is_user_abort :
    ∀ s, isUserAbort s = true ↔ s = AbortSource.userStop := by
  intro s
  cases s <;> simp [isUserAbort]

-- 3b: Internal sources never set user abort flag
theorem internal_not_user_abort :
    ∀ s, s = AbortSource.internalTimeout ∨ s = AbortSource.idleTimeout → isUserAbort s = false := by
  intro s h
  cases h with
  | inl h => rw [h]; simp [isUserAbort]
  | inr h => rw [h]; simp [isUserAbort]

-- ════════════════════════════════════════
-- Part 4: End-to-end guarantee
-- ════════════════════════════════════════

-- The trigger only fires for internal conditions, never for user stops
theorem trigger_only_for_internal (s : AbortSource) :
    isUserAbort s = true →
    triggerNew timedOut compactDuring timeExecuting (isUserAbort s) = false := by
  intro h
  rw [only_user_stop_is_user_abort] at h
  rw [h]
  simp [triggerNew]

end Example
